apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5
        env:
            - name: database__connection__host
              valueFrom:
                configMapKeyRef:
                  name: do-db-private-connection
                  key: host
            - name: database__connection__port
              valueFrom:
                configMapKeyRef:
                  name: do-db-private-connection
                  key: port
            - name: database__connection__database
              valueFrom:
                configMapKeyRef:
                  name: do-db-private-connection
                  key: database
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: do-db-default-credentials
                  key: username
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: do-db-default-credentials
                  key: password
            - name: url
              value: https://stories.{{ $.Values.domain }}/
            - name: mail__transport
              value: SMTP
            - name: mail__options__service
              value: Mailgun
            - name: mail__options__host
              value: smtp.eu.mailgun.org
            - name: mail__options__port
              value: '465'
            - name: mail__options__secure
              value: 'true'
            - name: mail__options__auth__user
              value: postmaster@mg.lovelustpassion.live
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: smtp-postmaster-credentials
                  key: auth_pass
