apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghost-creds
spec:
    secretTemplates:
        - name: ghost-creds
          data:
            CODE_INJECTION_HEAD: ENC[AES256_GCM,data:jYMBLRYPKRA8QZx41QDTLBn0uCaERdcp1sILFqlAzSfxwYJsrKfhFHIhlL+cdcE8djnfcxFd/7NRpYextam8XhtJynolKpK+WHLUkeACzZ6Y7clCRZdSLJrTbG3hEuPKVH8XPB4+rAvEteYElgV8s4be5JwsosjqniJvhmQ1yMInzn2ytaFCDnMvsi+AnEisdEYa5SZY5A9wRwZ3BKLK00mEz0pHN9eW1xAyA1RQAyZYlerrkxGc6X0KstDTJrtSMYLl2ePWOgNalfzIsmX1rV0cye/9kCNEPH61Mxpt7M8SHID8HD81AFukjyhZyjdO/efbbfBdmoAK5XJU6XLekF+82MsjK4OKOQUMXxLOaYpMoEcBT4Ge5bC2+LKvMoKPChLoRE4Np/yjY4NoTgoquB5mHBovF5HLs3TGdJrkbzMpymThEiH10VvcsHr1ixS88QHxrQd649i0JyvudilD+lJPj1buogpNic3tOeaWpm29ViEnw+cY7HJOMwmHmTrSE3V4Qi71YAe2YDn83abA4+f95IaVfvPVEQpb641rDNiD9FxsFsmEa7vQqum85uOY0+GQ7Gorbgs1WjqnCGnuO/LGLN7FgtgurpeO6E1q2TNvDTVXLpIDxIgbGxsbUiIQQgFGosDqfzcIsmn1v3ZhaN86mD1dm+hEMqi85pUd3eqWjBxyYpKxYMOq3TWYu+7HhCNYtpP5Ukd3Lk0GHNpCEmnoxQXThYPmPtl9j2k3T3tr7jISQgq0+/rLB5CA8g3napgJWaRgeIeScdwQv2JjTcZtYsicbcQHTVVGR2IpPmTFupoYyAV7jA48YVHzzplduxxa8Y/edBTAz1+NRjDY4SUmTBh805DALw1lkKl9Da09sN4Eee964zuJfyC4j1J2rlvI1s2Tg4HRFdF9WdGOLvFNADplinm12oYCQn6xA1TD139uzgaLQCZIddHyV0ruZ3Md6LAzLJM2/vrZRZa++OE8wTgb3Xc2zYlPvWZjwbPJ3nGdZ89cbDVVkEcUMlxDJw4uMI3sApULL5oxFBHyiho2ITBwy9ncnXcpEA7llQemrwZPvOPhkHGrPYOFzrDxK2OL///x2DcuweBSMpd5lnoQQdnIqEb4Pc8slHlQI3DRIPkrPJ0UdWN4uFd/8NLHPoqYtdEBf+xeUZQ1gJzFdZhW3q6amiyCuxYjg04rB4u3fZE1G7qDwp8C/f3Tx60mfboxITPD9JBm2xaz6ZjiGNeyR5roD46AdXVk0Gdt/4pax2O62lUyX2WDi28WCgsA+T4rf/ToXe7tBqchLHidQ2U8D3+Uli1RO3Q1v50JToABmWyYxS62UX5FhWozF1NEWiVX3/Y50CItfCDRTQU2KdCExx10cEksOCDHe/sdZFUkRAjlna/5B5TUknNHJEgUjCrd1dmr0f1soNvoysnb/9C0uUa0eRqMBXY03DElTkDeRbQAjlEzIXsSKqyNQEdzOJeT9z0YNCHe6Fc7kjLNjVzr6imlFtSUYNWgGvRJIfBYuqnxzX5fvHBFoQF2WhBtWISRvPtSJoQ7lKuDO9guLT7+jZMaGKo+smFX1hISYZ+fkmYoOXl76Q5UNijcT8fcGNED3JYgaTdPtpxh2LHIyXffMg3LA3+RmFUhrzxiboEfsGrGdsiq7zNausql7nMaF2DgFMIDn2t51QR0xxzTceLh9wz41YUKGfShPA0+Dd0e5tIKcdVCJi5R858TzEtZfI36o5nxy/yKmtB0UX//En6IqWVXEI/Qaarjtou5Bs7NOCeedo6RrLc4Umjn14E3yfQKSpEFNiPxGbW1o9jZ1Nhj0j/M90IlaceDdnAz2peeAuonz/M7Wav7Qu1P5HxnRdRa322Rr8geZV4ki727XnKo0WncOuhJiwMIYlybjwW9keFNFk++wSHu7GW3aK6qJTOhw36b+Aeclfz+kECugQ0xUZS1fl/i9n/VakogCW4eqGV/zQTfOFFzU7xrx71nwgDVaBVwTQngg7tUXqUD4A==,iv:FD5AFQvUMvuIGXj2LuEd5f4G3NDqWsagy3GwSwML1f0=,tag:5Fj2hTyk4j4ahNlyalx4EA==,type:str]
            OPENAI_SECRET: ENC[AES256_GCM,data:jqyh9R1rJRJyXkjjJWNmPu0BrruVn/yKXcCZRc/o3Vc/fdGqHrN9gmpbkjZq+DAhOM6uKzMJMW9Z9CHKcewAiCz84ms=,iv:xemycs/SUy8SlUmLFEBxxKJTbZWCm1K/st6qEejnNYU=,tag:V+H4ieb8iD0B1AFzF7D/nA==,type:str]
            GHOST_PASSWORD: ENC[AES256_GCM,data:/ecNGhMH6sBs2O9+/YEqPw==,iv:tPYVXkO/aX48sTs603iF0eKpYh5HKZQuqKHFymeZ7n4=,tag:JkbavIZThNLqjO6L9Pmg1Q==,type:str]
            MAILGUN_API_KEY: ENC[AES256_GCM,data:vWLPq7oBWyOe27g0n+UAR6Vpmc+weLe6Jqnbh9laHmGs7/R5bK+aDMLZapoR3mKRRqW8kR2IU0k9IFpRgScdga09CX0=,iv:f59UfeUZOn4HN+GSoUYN5x9pKFyGW7ilWuAeLLeEP8U=,tag:u2sKZ9lM49dzNlAlQ+pieQ==,type:str]
          stringData:
            MAILGUN_DOMAIN: mg.lovelustpassion.live
            MAILGUN_BASE_URL: https://api.eu.mailgun.net/v3
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHpPeGFmOVpuTDk0cGUx
            dVV2TGtUaTBIbHkxWnlXRlQ1dUhYQlUvV2dNClJUSVBVUURDOWNmUFQ5K3VRcERp
            UHhEZVJmWXJPQk5GSnJ4Q1BIc1VSYnMKLS0tIGk1YjdTU05HaFRrWW5oTWhEMW1P
            WmN3aEZFWlpFeTdDZ0lSVUdOTkNBa1kKrLZkX9YmkqjVL3autGOiW45g8sSW4TAU
            qwUNursU9zj1W/wke5BNUALaNUxlsAaYrd7A7hrA2KY+Rmkqvm3DCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T14:12:09Z"
    mac: ENC[AES256_GCM,data:/hocH2BVImFMub2lAm/4ypZ6HxvQklu8RtzLTcm2/+2B+Krnl4rDkc0NcpjuylRdqccLZXl2obkrcyqPtsUYjCby8UHM7+EuqlIrt/mS/Ymg+/qYXyJe0FEsQ3qmP9ouorAUS0ZUGVwBhpF+276JcnLBHEgvQN2nt/CZxPfTmLc=,iv:ziAhsppOOYQpFglnxiUlGy4hOs6cWfUwXbwwAo2TDqI=,tag:EpzKMzzYKHJSXcCAbmgPLw==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
