apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghost-creds
spec:
    secretTemplates:
        - name: ghost-creds
          data:
            CODE_INJECTION_HEAD: ENC[AES256_GCM,data:UjdePQQCb3JvAmgXWZ7vDzZpADsMtE4VYofc9LK3MKvqelMRkAs9wMm6d1mcdKwbEecQVP9B64SSzLM1wHbry/lcejPNGwdBwd/ZQo6fV8Of0Ao9Xi0Z18RUY1px86FRHtJgErPM4BFLTcVWGM1uA7PpWFvYd7EOVNvLeL0SMAptWn2F7B5EsSiHcyLIBxvUvXxIjFoCv6je3LOtKktLXNKvlyPb33xsRPbS6xOgDpNfosgBMtkE9J/YP1tog303x63D+KfJ5OfHW71LmgX/GD4OP+yAu+SNMuGaAPQmxUi2+40MuW9uzJLynB2i1AiPR0b/NWSCnan1ummIAsm029YNih+NzY96OL1QzMZVEGPsMHsHpdGsRU45yc+OvyaondXp0XXm5ioL818JGtL+CVZVtrCvcfLJ3KqMmP6x17XKo469fnvL//LCYcIjavRrfkqkRxuN82ean/8cnumroECTxFFeEsSjOasIy/B0EyHK+AcTzYXbV/K3a+y1471LlplSd4BJcXadK3VqYy0DMmlXXFmxwvUT3LqZWDDeAy7FZ+G8hK8h2dbghgQ/3h4Mfz5lAy6Pe9bObv2AwsHxrlpH/BIASw1vOroF9k6VAtWCPNAMhHZLexwLVIe7JAFPCRlOd4PaQguaqn6esWbOsguW1BVeTXeMMKqw2eE2OZwHQPKl5Mk2d6BJ4oEaI665/QVu4e/U3Ya1ZqpN75/nptrAyyZzDo1DWjEV6QH0i/iyQfXY40wQpfDM1XHcob+LnkO+nZJp4WDbtHdabbPSwYcBQ4NT7XSPfhMFPqEyEcasZfP10hR12Lum677vQeADrsn7KDAjlK0K/3mbP1EHQYrowc4QRrcbz696VsBtXJj/fm4DSJCKK2eVJ+GIJ9jbmvZ2Ff6e1PCbwz/NXfZ1SxtIeerY4g7QCEyvbnpxxCKxPM4fYuKdB38WoyzGhX6/TsMYmn3rsV7UQ30zW3EQkAzBfCAw3qd3/AzLLr5P9grdT9/76R2gFAv63B1N1Fs1XfisfGWtjwQ3ThpOvZqPNzYKJnhm7uK2bjmg0tWzx830L7YyktvbP7yi42UyFmMLzUuWQmh9Wkz01ZJ5vkb70GHLUkGxbbpL6ncjMPJ3CqS86L1sKj4rqG7WmdbYQstmE1OoYzHkgdDwhwW+GHslwyCf4bAWVqtQFe3TdXjH40S4L+7N/2y8P6kT7uQD1+duFDiUN9QpY/Yv4IMqfxIbaqRDwZY2zLyPZPb09j9/BQ+XhjcI/O4tt3RVlgpjGDo+DC6MTKg6KxyF3xuu/13QLirSJL1wGqaO1A+JjjkEJIMW3sTRfB76pM9OE0MprzPrI9/2PVQ/U8CS6h75ZSHhVCJllk6dVsfEyUeyJ25JVTv/AmHddJLYh0XqI1Jxq/uVBHjK6w61wOPxncmgzRmdMJpX0mdoNeRypuygwhXxQmU4nPclRtIwtJbr6Pt/CUEURZ1CArZQ5aIbPnesdCnw1ZnKFTgf4J7J8LkJ3Ry0t9NWrkR4eUkKl0vIAdEfrQ//k/pFn14cRt8iGc5nVwNaVBUktLDrqFIwFBUt1FU/E5RQf2OJB/qahIZr4wJQrUqlW6Dvk8vleF6yLmGzicjhXwJOHHMzUrh2ehjbsJy6elChyyX5PD0LTecsqDq6yyj+JGRGihRcH/35TU17NEuSHOpSFKwpCjQ2qiL3Vo6Y1sJM/iSnTfCCsUw9fSN7QgMtyNYEkNPyPOdN3G6ZtO2jZDy/yHhS8/y844h+1y+94hFZcb65bahDSBMNV76cN/iuy6JunG5qocV7XcwhzyIL9bjkLYxtqmFzxIcymL769bM53M6GsbZlaIamiGbtMR1UXF3Ru0BV98bXlheySQ2wuWYOmhJEDs+M/xxq43MXsaxRFC5sXYqGE7esxqmP1efuG5HAq87t+S6XX8wkGkYtgsriMDUKc4G/vQfgH5vQHoOO4V1MyuuFwN6dNiRPenIzgRK1Pd3ObiPgATsSnuP1K4QHB9bYo2YQtPWDxh9pTjqpX2PuKxnwC4FXCyMRFmmN,iv:MTy6dvaNQQSN0vEJ6DaqYDZJGK0vZLHrvD96QP6dr3U=,tag:GAUWPpPjY/3vxFQve42Muw==,type:str]
            OPENAI_SECRET: ENC[AES256_GCM,data:jqyh9R1rJRJyXkjjJWNmPu0BrruVn/yKXcCZRc/o3Vc/fdGqHrN9gmpbkjZq+DAhOM6uKzMJMW9Z9CHKcewAiCz84ms=,iv:xemycs/SUy8SlUmLFEBxxKJTbZWCm1K/st6qEejnNYU=,tag:V+H4ieb8iD0B1AFzF7D/nA==,type:str]
            GHOST_PASSWORD: ENC[AES256_GCM,data:/ecNGhMH6sBs2O9+/YEqPw==,iv:tPYVXkO/aX48sTs603iF0eKpYh5HKZQuqKHFymeZ7n4=,tag:JkbavIZThNLqjO6L9Pmg1Q==,type:str]
            MAILGUN_API_KEY: ENC[AES256_GCM,data:vWLPq7oBWyOe27g0n+UAR6Vpmc+weLe6Jqnbh9laHmGs7/R5bK+aDMLZapoR3mKRRqW8kR2IU0k9IFpRgScdga09CX0=,iv:f59UfeUZOn4HN+GSoUYN5x9pKFyGW7ilWuAeLLeEP8U=,tag:u2sKZ9lM49dzNlAlQ+pieQ==,type:str]
          stringData:
            MAILGUN_DOMAIN: mg.lovelustpassion.live
            MAILGUN_BASE_URL: https://api.eu.mailgun.net/v3
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHpPeGFmOVpuTDk0cGUx
            dVV2TGtUaTBIbHkxWnlXRlQ1dUhYQlUvV2dNClJUSVBVUURDOWNmUFQ5K3VRcERp
            UHhEZVJmWXJPQk5GSnJ4Q1BIc1VSYnMKLS0tIGk1YjdTU05HaFRrWW5oTWhEMW1P
            WmN3aEZFWlpFeTdDZ0lSVUdOTkNBa1kKrLZkX9YmkqjVL3autGOiW45g8sSW4TAU
            qwUNursU9zj1W/wke5BNUALaNUxlsAaYrd7A7hrA2KY+Rmkqvm3DCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T07:13:03Z"
    mac: ENC[AES256_GCM,data:GYrUsFaFHqSKfEKJQE/pCv6dYzGzGZ9LOFCYwvx+11BsekoZvw6n0rHETXvw+xMYHtg9dcpYBgJPsWnd24nd3P/iQYC6g543eDXFiHeU63tjFS7+/HIhseinXiENkfZiKjE6zR6qjVfhqKrAIXGHUA4AsRTvtMZfUQX9tC75BJQ=,iv:j5lLYtgy0Cg2KaCjy3U/MG8A6LGtXWCd93Y+780ieU8=,tag:P3fOn5TMv4CAD/0hrx8ceg==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
