apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghost-creds
spec:
    secretTemplates:
        - name: ghost-creds
          data:
            CODE_INJECTION_HEAD: ENC[AES256_GCM,data:MZ7/IN+4kjbo5rfHJFg8D8ta1+hJauB+W1kM3a0KwFeGlRWwXYXsb4MTxEtGvpBxf05N/En8dfQ6odPWqOjOk7SYfWuBplS3sCO4wJWAPQ/YlOdvVU0xu6eKqQFJheHAaW4mXzBs702bu2xGVXz46eBszNwjS4JGaOfX9uOX0eA2sUP5qeAfF7fz5nt1JhuMDEwTLhYUX9I315T16LZe+q2OyXko+8+aUmNa6OLKfR1dIF3fTaqS6Y927tLLiT9WF+s9pCb+S/vcBAA3eMApbd1vLtyeGS9KhwI4Srk8hNcR2bOsWbhL3X89Ju4tKFw7QmedJ2fLbs8NkB7kOBTiH00GZ3rcNwv/6mMJmJIB9VYi0xAO2eBOGSDU1pzAWLI9iGIcgT2HVY8NrryBZZsd8ffQ+Zb4Aj5RXFhCC2Q0bUDT9ABcDzm/W2BskekOI7HLqwYaLyYHNAHEwyaTFC6U0CTgyarW17N3IfdGxv7mlrlnp1uskNRVoR4Z7oib7XckOPHGUfEW+2F02hwuRSWWfIvuZfHI83cLbcnKMmuBXThF4PhLLxrtByf8LgKRQ+NoFzbajUP6gw696mWWoNmGn8BFS4/KKL27l0EnsQCCVnELsz1zsK8tfgzdzPChiR/TGF9aZz+zUqmcLxNUJeJLlcbMGtiNyux81B5b/fJst1L5NQFcsQS8qtwbv2E5J+T7rO0Q9gLBmwzOiMZ/CzAU4rFxbjxmXzRf9hEutLocF6qcM5dN0bCswcwkN+tJ1yuO8/hhqIf3JLMdqwkr4fURTRz7IH/y13BY4V5fe6YppRIEJ5fgH8HX7gSiN0ZEMYp65XcJ29vXcBEOWxFR5wyNgWVKHckXo9uiFIOk0gUYlhTiZY48+uR+WzCJS8uCA4ZFlk9zRY7qgqDqfUdn5Or1tIz7KAYCRnjhmam53Y7vle/ygeC6lHv2Tf1eKMqcbMyweRnXBfjyX7fm55WPFEYJf9vtPbMkkKv1oAFbglB1GbOWXkNJOwHejNTMo8Adx+P7JET7jLI9llzQz+cID4UUWC4ht1yAsCYjYR3hJVU2bc9KZMy7y16FvOXnJquJo+1wrQ4U66GoZ/CYpX656RX6aYt8t7puMbcGjv5921QS/YfOuWgDMnxoGBDrWeT2XbPsTAORNqZqwOXjhnUEr4N6B/4gbDKpDmx10pDRhLUwkv36OLlMst7A2QO1HFHrYLWt1IM9baCaj0/4c99gU8SXS3Uyju7WbYZJK5YoeJudqvUOfuO40MnMpkcaWyj3ZkLHODUjRfrq5Hob8oAUdSjVXt8Nuak0KGUFaOzGUw==,iv:QPRdHbGiMzYor55hw6FU9D4w7rqB0TSi2p+TfPyWohA=,tag:se51s2NG98tDmc+8H7p6Bg==,type:str]
            OPENAI_SECRET: ENC[AES256_GCM,data:jqyh9R1rJRJyXkjjJWNmPu0BrruVn/yKXcCZRc/o3Vc/fdGqHrN9gmpbkjZq+DAhOM6uKzMJMW9Z9CHKcewAiCz84ms=,iv:xemycs/SUy8SlUmLFEBxxKJTbZWCm1K/st6qEejnNYU=,tag:V+H4ieb8iD0B1AFzF7D/nA==,type:str]
            GHOST_PASSWORD: ENC[AES256_GCM,data:/ecNGhMH6sBs2O9+/YEqPw==,iv:tPYVXkO/aX48sTs603iF0eKpYh5HKZQuqKHFymeZ7n4=,tag:JkbavIZThNLqjO6L9Pmg1Q==,type:str]
            MAILGUN_API_KEY: ENC[AES256_GCM,data:vWLPq7oBWyOe27g0n+UAR6Vpmc+weLe6Jqnbh9laHmGs7/R5bK+aDMLZapoR3mKRRqW8kR2IU0k9IFpRgScdga09CX0=,iv:f59UfeUZOn4HN+GSoUYN5x9pKFyGW7ilWuAeLLeEP8U=,tag:u2sKZ9lM49dzNlAlQ+pieQ==,type:str]
          stringData:
            MAILGUN_DOMAIN: mg.lovelustpassion.live
            MAILGUN_BASE_URL: https://api.eu.mailgun.net/v3
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHpPeGFmOVpuTDk0cGUx
            dVV2TGtUaTBIbHkxWnlXRlQ1dUhYQlUvV2dNClJUSVBVUURDOWNmUFQ5K3VRcERp
            UHhEZVJmWXJPQk5GSnJ4Q1BIc1VSYnMKLS0tIGk1YjdTU05HaFRrWW5oTWhEMW1P
            WmN3aEZFWlpFeTdDZ0lSVUdOTkNBa1kKrLZkX9YmkqjVL3autGOiW45g8sSW4TAU
            qwUNursU9zj1W/wke5BNUALaNUxlsAaYrd7A7hrA2KY+Rmkqvm3DCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:12:06Z"
    mac: ENC[AES256_GCM,data:q/rRaWa9CXejc/ewqYYcGnTD1Q3Pi1j9jl4eGYr6Wlbyf80XgYYPk5Cx3HUL099VWPaROe+0TZdW4WzI7QRvdB9l8SjZLJf5Mugr0rCu0satj5SYyqKwt2PE/hxvTHF6Yu5X9qHnCgKIgiqJkZ8d+b0CpZJjXamhei6JbG3vhjo=,iv:m2nsXwdNgaLc0RlLa4M8PvwLgnWF67JwP8iXvfY1OuI=,tag:HtdI8908+vMor4nKei8dAw==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
