apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  rules:
    {{ if $.Values.prefix.enabled }}
    - host: {{ $.Values.prefix.value }}-stories.{{ $.Values.domain }}
    {{ else }}
    - host: stories.{{ $.Values.domain }}
    {{ end }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: ghost
                port:
                  number: 80
  tls:
    - hosts:
        {{ if $.Values.prefix.enabled }}
        - {{ $.Values.prefix.value }}-stories.{{ $.Values.domain }}
        {{ else }}
        - stories.{{ $.Values.domain }}
        {{ end }}
      secretName: ghost-ing-tls
