apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghost-creds
spec:
    secretTemplates:
        - name: ghost-creds
          data:
            CODE_INJECTION_HEAD: ENC[AES256_GCM,data:77mntAX5965rgsMwjb2fFzsrDWiAZpy+vfyPvxatS+xgNSp+EeoGRGy2+ewt294khiWB7CqKkBOM35dfR8Auj+3z33Dae8+qwZOHhA8fdQzY+3MiQf/JeEba+1GbWqkwdrlIL8F6Csrah61j7bXTSuUnWpBXI/euoE2i0fXaWQAL1jAmmss4IPr8kU1kvqN7OCVFDuqZayxf6Pe7t/OSycHwBbph7CHUeWUSgPEojNevnwrrBFXsxJdJm6B6Z0zpUO/VuKpsHsd2iu1CWCdnI42b8cw0f4/OdluENrTWtC7d6HEFpiUlehU+aN5iWg5JHOlRV+Z1oomkth3BipAZWCVILkLfjr567Q8phRnPNh4pJ+oKyvI98eu7j+y44jCcu/PKY5yuXiMV723+r9Kuyy8XdK5MxVySf8a4lMlCZj0vKg68dfeVQaFJ6JhqlhPmVokH3cLWnVpS0gYspWqvMCIHZrGyZ/l2NyQIvcbPo6rJVkcuFj9916y41Vxw6emJmKDXco6IZ6rumNvqyY/dFwxpc84DPwiF8ilDXU3Dm8wPLApXbC+0SXwwlkEepQIAjUXS5AiSc7yYp+oSV/nV0bcB87SGVdWGt/z0zjEdvLvpNy9EqdKFVl18tDJghObsfj3xYd60OfiwGSRDhTkg0Ri4w3haQCeikyzY7CYuZYdj0A1xhzCKe+AhSe0qCbCQ9tLP7paTH4t0qDPlEEDUCBD9cOCjYigOCGJa7ZHt40HriVjQ5Ph2N2vXA1VxayDrZ9Pwsdy/67iX3J7x1umEAm4eTdkBqcdlhKj+fnmgrKZ7PbtSvOksQgl6Zmx4JXCz+wQ6kHCSklIPNgB13TV+QV54E5bnmfaHrvoIy1aP0tioD2n0EADBJfPbsKmYxwbSS1lSe8uGoFtBTVSoU17zlzPG1J09jxvzo+jXL1e6o3ydX0ONFwB3EFkYIHYA+/4aqTkISz6jn3dy3g9NF6c7ZPbogYZJF9hwgA4Vq3/ptj4jHy8KGorucSGAkkO3wG68N6Te3kb7MNf0tBU2bBGKcVTPCKKLIEAH5EcllpdDK54K3V/hOLfTDZiv3cx0tRqTkbLVleElpJIPKudf1PG6FWEBpEVPTBwq5NocDrcSUQegNLq3lyVWZSNfl+lYlOqy2H5k3U4vH89t4+17ZQeXE2ylye7sLrIyWOVJ56Fn76UhziwE4Tav9Hcq0PLEdmvFt82PpRjk9ZNzx2astcBoY/eu5aHnIndWT+QEfy2okDg5pY/grAU5dDWKzVFyL6W+oZy6FQXji5k9HKIBY4HfWc7OZPWKrVXES3tzDaRttCEMsasw6C9k1iWfIMqemEg7wOhmjB0kuBRfrBBYHnGZPz0gOTyWOG8beDsypCkPvG3hlIhfJ77c6ouwM8I9u5r4Ee+qWGss5xVXXgTTytwWqTiUI4OjB22JKqY/7JEhoWcfp8DsPhQlrljfWswztYbRk9RD6Zl+ALerxLOCSDsYRcu6glr3GJtn8GikdmERPj38yGHpoethSmMGJK7ThQW7N2XlYmNTHBDSFG1+RI0FQcQeZcJA6mJrrP5P/pQj/74cHA3+l/1F0QXt+FLlOpWIXTUaJJ+DiGFYQ6QcQL73jjZjAlmRLYYzlAK4QwBUi0g2WRGB4s79UcE0kAeq5IdtsLPZKXsU8+b/FW3lrZZsUR/tPexnxVy3Kgxt7icA8wW6huxXCzSj7DBzfKGYx3q6bg+opQZbkZxgfp32FH3S0nczhvyb5JnC6AmC7n5JiopLcLUiP7+YcCFRZptBvFFtZ9xHKD1A2cj+yXdwgqZrJqAxKAkHbNkf/fY7scV0cyAidWd2S9ECC+QjT5RvZQIXSlr9BwbOkDgHhAPlQmKZgtHQBXOOTk5qQIfc/O81kTyeLlXuafRgCr8qDz1emE5zwhilacLFG6D8B9UeQZ3M5XcOeatXiYSakntMbvRvS6L4d9CpwGf4w5VdcSQvLF3CJ/SW+pQ7TjnUnV7aGKFg6yZAzQS3rssQKBD2QMtJYdFU3F+DIf+0M90iQfyq2lXrspAL5w==,iv:oEh8irt39FrcYh94bvUebBr3yOOI1//gPivZQaGndVU=,tag:HT1odUCJkhWt4lxaXEnk6w==,type:str]
            OPENAI_SECRET: ENC[AES256_GCM,data:jqyh9R1rJRJyXkjjJWNmPu0BrruVn/yKXcCZRc/o3Vc/fdGqHrN9gmpbkjZq+DAhOM6uKzMJMW9Z9CHKcewAiCz84ms=,iv:xemycs/SUy8SlUmLFEBxxKJTbZWCm1K/st6qEejnNYU=,tag:V+H4ieb8iD0B1AFzF7D/nA==,type:str]
            GHOST_PASSWORD: ENC[AES256_GCM,data:/ecNGhMH6sBs2O9+/YEqPw==,iv:tPYVXkO/aX48sTs603iF0eKpYh5HKZQuqKHFymeZ7n4=,tag:JkbavIZThNLqjO6L9Pmg1Q==,type:str]
            MAILGUN_API_KEY: ENC[AES256_GCM,data:vWLPq7oBWyOe27g0n+UAR6Vpmc+weLe6Jqnbh9laHmGs7/R5bK+aDMLZapoR3mKRRqW8kR2IU0k9IFpRgScdga09CX0=,iv:f59UfeUZOn4HN+GSoUYN5x9pKFyGW7ilWuAeLLeEP8U=,tag:u2sKZ9lM49dzNlAlQ+pieQ==,type:str]
          stringData:
            MAILGUN_DOMAIN: mg.lovelustpassion.live
            MAILGUN_BASE_URL: https://api.eu.mailgun.net/v3
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHpPeGFmOVpuTDk0cGUx
            dVV2TGtUaTBIbHkxWnlXRlQ1dUhYQlUvV2dNClJUSVBVUURDOWNmUFQ5K3VRcERp
            UHhEZVJmWXJPQk5GSnJ4Q1BIc1VSYnMKLS0tIGk1YjdTU05HaFRrWW5oTWhEMW1P
            WmN3aEZFWlpFeTdDZ0lSVUdOTkNBa1kKrLZkX9YmkqjVL3autGOiW45g8sSW4TAU
            qwUNursU9zj1W/wke5BNUALaNUxlsAaYrd7A7hrA2KY+Rmkqvm3DCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T06:58:49Z"
    mac: ENC[AES256_GCM,data:nZO1ugTJE9UXgTHPAKg5F1XnFuv8b4Dr/1XUWcvOSFCnqMPWAXc3MhY3AUWAwbnQ/9taVumpyR5HeI2/fNin3MXhAJuNthHObm43t5sHslhPbM/kMTbFS7tOG8h0/lSAKUOyTki4oOtknYrWoHkWbkAQE7GfMatwGlMQIabAhr8=,iv:6/IHesAXIzoq5BoGfCwpbsdKs2cCd5On4zCTNBa2k+U=,tag:ZMa+SLkc4PHfFrSUVUQIYQ==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
