apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
    nginx.ingress.kubernetes.io/server-snippet: return 307 $scheme://stories.{{ $.Values.domain }}$request_uri;
spec:
  rules:
    - host: {{ $.Values.domain }}
    - host: "*.{{ $.Values.domain }}"
  tls:
    - hosts:
        - {{ $.Values.domain }}
        - "*.{{ $.Values.domain }}"
      secretName: landing-page-ing-tls
