apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: regcred
spec:
    secretTemplates:
        - name: regcred
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: ENC[AES256_GCM,data:J7B/1Ulu/kos0KZY0Y3y+7onOsIeRNtolbS5c4GLaa9ZhXN2mfbNOAm6SpWxMkPlalz7BNyLCDcVfO7VpcDaQ6xapRzu+eGDEcw1t5CYUQZILVRFbsIROhvr8JD00lRHmFxI+IrMCB8ZZRFrIT0LoM9TMWReR3+breoJMLqrRvebW/eo7auIEeqkK/of4XqBNS9XYIctHdpSU6jTUFdVe9uWje52pBkjSAlHYNHeJMSlP9+02mdd4Zu9i9763P1iC9t/qeTPH7i4CN4DJ9yDUNJgIMflAnvTxrXpCOWAsLK/gERIIJijcERDu2lQ/GYwGKr4MlNIIAlsPmcieCHm6+CMSk5Upx4veC7En5emcuYLQMUoFE7hdcifpHJzTJsAb1dDXN80JY02zlOa0QM9I2yhcniTIyufCjSQ+Fnwxxz3aiLU,iv:fzwySeBsb4+jTaZNYtOjFOlWzxOIqLBP35KxIREHia0=,tag:fOsaaxB+aVPVhssvYKTHgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHpPeGFmOVpuTDk0cGUx
            dVV2TGtUaTBIbHkxWnlXRlQ1dUhYQlUvV2dNClJUSVBVUURDOWNmUFQ5K3VRcERp
            UHhEZVJmWXJPQk5GSnJ4Q1BIc1VSYnMKLS0tIGk1YjdTU05HaFRrWW5oTWhEMW1P
            WmN3aEZFWlpFeTdDZ0lSVUdOTkNBa1kKrLZkX9YmkqjVL3autGOiW45g8sSW4TAU
            qwUNursU9zj1W/wke5BNUALaNUxlsAaYrd7A7hrA2KY+Rmkqvm3DCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T09:23:58Z"
    mac: ENC[AES256_GCM,data:dH4vjIHdk7mipL5Vgu4SQzdO49BW+5E40NXWFR18g5yxXLYs9xaY3q+zaPyPmQyNEnrisqlxPdjkgBQ0lNrVhZjmoedEarYgNFrDraKqjoN+QgQ/XKMfkAP/hLJnCnNl5JkD8BYsDdpB5k1eLzS5ZQu82TlpRLhQIWW9uf+HpjU=,iv:6CyuC3nyKoe4KYpa6OqWMtjbBR7cyFdN9D5JUqvFV+g=,tag:vsR2VjY5r8xsqzF7SKWJIQ==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
