apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: s3-credentials
spec:
    secretTemplates:
        - name: s3-credentials
          data:
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4KpHT/CPBFGMnWALNjXHVocMygfVP15Kr1V/UhFOlvD2ciXUKpBMl1I0jBV0c8gPGzm6K+OUb1iZU619,iv:wzs2LxPA2zHT4zoozezln1147CVV6PnSqdWoOzlxfNU=,tag:TfEIeKKouVYB8ne0uJMpTQ==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gPi4bjttYDwFgw7v9EuOTzbRHokoipSa7C3V8Q==,iv:whugIqg7zroLHD6hagwjJX3NWTqfJsM4RWW8TkXikPg=,tag:i95gfk8ZwM79rXijvEcRYw==,type:str]
          stringData:
            GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET: '{{ $.Values.doBucket }}'
            GHOST_STORAGE_ADAPTER_S3_ENDPOINT: '{{ $.Values.region }}.{{ $.Values.s3Endpoint }}'
            GHOST_STORAGE_ADAPTER_S3_ASSET_HOST: https://{{ $.Values.doBucket }}.{{ $.Values.region }}.cdn.{{ $.Values.s3Endpoint }}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ0JHQVJxa0FLYzdGVVpy
            dUZLeWFPd3oyU1pSZXpkYWR0eE10aG9iVFhNCmgxTG0wODhab0pFYi9WVmpEODgr
            aFJqYXdZNXBxSkt2TEI5TXlXY2ZNSkEKLS0tIFNyQmJIR3BobzhZcU9JVHFFelBn
            dTlDN05qOXNpYjJTWVptemxBakExQUkKIhPzYFH+mU/IkTyjk9nkbTwTfYcgyE4b
            5e7JCukI5bSvHHlIJL5+zkxQDE0VuGGv52FNt3dENHFn6xUFsxQfGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-16T17:19:20Z"
    mac: ENC[AES256_GCM,data:KJ7j/8D5wsvF5VpkQvYqxLdkt5F7tL/MD0NHBhCLzjKOpgvTJQ0pd2aLWsKed+8ImUQUZc6wNcYB9Zh/HkuPv9NnGeT2McQXABpx4zhwKZbRB+AxUwl1XmTe+f0H7c1hXoAwm8LcR1ngOR+z5bPvGnvA5ZqnlquimKSmgUCz8o0=,iv:0DEgfIyB1UhS76ENenoMkPuZ4NZY4RCr44u6wlbPmR0=,tag:rYS/r039qavjYbH9HIQXxw==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
