apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: smtp-postmaster-credentials
spec:
    secretTemplates:
        - name: smtp-postmaster-credentials
          data:
            auth_pass: ENC[AES256_GCM,data:1CYv81YxOlW6n9sH7YkBJ3msm/KbjHACkkytJEf6GGXv1MSTKFNC13h/4P4MZDBjLdszdxi57TEWWrzStH2J2ewJeX8=,iv:NGp/QYRXCxVx3mA/y6HQMKRDk03P1ZVINi+A0VcBdW4=,tag:Y7A7RuuamAM1G0lVAMJuOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RHpPeGFmOVpuTDk0cGUx
            dVV2TGtUaTBIbHkxWnlXRlQ1dUhYQlUvV2dNClJUSVBVUURDOWNmUFQ5K3VRcERp
            UHhEZVJmWXJPQk5GSnJ4Q1BIc1VSYnMKLS0tIGk1YjdTU05HaFRrWW5oTWhEMW1P
            WmN3aEZFWlpFeTdDZ0lSVUdOTkNBa1kKrLZkX9YmkqjVL3autGOiW45g8sSW4TAU
            qwUNursU9zj1W/wke5BNUALaNUxlsAaYrd7A7hrA2KY+Rmkqvm3DCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-17T11:01:11Z"
    mac: ENC[AES256_GCM,data:sNgnZI//V7gfO36+wSHQlcclpNd20h7rRUXa2sIGgbEZ/JWnqUogZcOJwWRyRAbfn7sTqQC48WMCsxvSc004TlvwY5DEDlJ8PKTnMlvAwK5PuySGS5nnylA3WLELGNUQLEXdJUIcYdwG/ULxtulpFeULH56Mnulox1BqYbaiMdk=,iv:2aBX440+HwryhEzLhmomVzKIr3Na0gdq/CRaQknEkek=,tag:ubPebekWr/AVEs+YlxwMIw==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
